MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  MASK_ON: True
NUM_GPUS: 1
DATA_LOADER:
  NUM_THREADS: 3
  MINIBATCH_QUEUE_SIZE: 6
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0015
  GAMMA: 0.1
  MAX_ITER: 30000
  STEPS: [0, 15000, 25000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ANCHOR_START_SIZE: 16
  DIM: 64
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
  RESOLUTION: 28  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
  DIM_REDUCED: 64
TRAIN:
  WEIGHTS: data/R-50.pkl
  DATASETS: ('med_train',)
  SCALES: (700, 800, 900, 1000, 1100)
  MAX_SIZE: 1500
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  IMS_PER_BATCH: 1
  RPN_MIN_SIZE: 2
  USE_FLIPPED: True
  SNAPSHOT_ITERS: 10000
  # FREEZE_AT: 2
TEST:
  DATASETS: ('med_test',)
  SCALE: 900
  MAX_SIZE: 1500
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  FORCE_JSON_DATASET_EVAL: True
  DETECTIONS_PER_IM: 200
OUTPUT_DIR: .
VIS_TH: 0.6
