MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  MASK_ON: True
NUM_GPUS: 1
DATA_LOADER:
  NUM_THREADS: 4
  MINIBATCH_QUEUE_SIZE: 16
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025  
  GAMMA: 0.1
  MAX_ITER: 90000
  STEPS: [0, 30000, 60000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ANCHOR_START_SIZE: 32
  DIM: 64
  RPN_MIN_LEVEL: 2
  RPN_MAX_LEVEL: 4
  ROI_MIN_LEVEL: 2
  ROI_MAX_LEVEL: 4
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
  MLP_HEAD_DIM: 256
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
  RESOLUTION: 28  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
  DIM_REDUCED: 32
  THRESH_BINARIZE: 0.5
TRAIN:
  # WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  WEIGHTS: data/R-50.pkl
  DATASETS: ('icdar_2015_train',)
  SCALES: (800,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 64
  RPN_PRE_NMS_TOP_N: 600  # Per FPN level
  RPN_POST_NMS_TOP_N: 600
  SNAPSHOT_ITERS: 10000
  IMS_PER_BATCH: 4
  # USE_FLIPPED: False
TEST:
  DATASETS: ('icdar_2015_val',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.7
  RPN_PRE_NMS_TOP_N: 600  # Per FPN level
  RPN_POST_NMS_TOP_N: 600
  FORCE_JSON_DATASET_EVAL: True
  SCORE_THRESH: 0.5
OUTPUT_DIR: .
# VIS_TH: 0.9
